/**
 * generateWitnessConfig — the rung-1 witness register (CS.1;
 * CONTEXT.md "Witness lights").
 *
 * Emits a Home Assistant configuration.yaml GENERATED from the
 * pack's needs list, so the test fixture cannot drift from pack
 * content: one input_boolean witness per declared lighting role, one
 * scene per role setting its own witness on and every other off
 * (one-hot). "Which look is live?" becomes a single state read.
 *
 * The simulation profile binds each role to scene.witness_<role>;
 * HA derives scene entity ids from these names, so the names ARE the
 * contract.
 *
 * @param {Array<object>} needs - from collectPackNeeds
 * @returns {string} configuration.yaml content
 */
function generateWitnessConfig(needs) {
  const roles = needs
    .filter((n) => n.kind === 'lighting-role')
    .map((n) => n.id);
  const witnessOf = (role) => `witness_${role.replace(/-/g, '_')}`;

  const lines = [
    '# GENERATED by scripts/lib/witnessConfig.js from the pack needs',
    '# list - do not hand-edit; regenerate when pack roles change.',
    'homeassistant:',
    '  name: Rung1Sim',
    'frontend:',
    'api:',
    '',
    'input_boolean:',
  ];
  for (const role of roles) {
    lines.push(`  ${witnessOf(role)}:`);
    lines.push(`    name: Witness ${role}`);
  }

  lines.push('', 'scene:');
  for (const role of roles) {
    lines.push(`  - name: ${witnessOf(role)}`);
    lines.push('    entities:');
    for (const other of roles) {
      const state = other === role ? 'on' : 'off';
      lines.push(
        `      input_boolean.${witnessOf(other)}: "${state}"`
      );
    }
  }

  return lines.join('\n') + '\n';
}

module.exports = { generateWitnessConfig };
